# Generated by Django 3.2.7 on 2022-02-27 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20220227_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitpay',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
    ]
