# Generated by Django 3.2.7 on 2022-02-27 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_bitpay_passphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alice',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='alphawallet',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='atomic',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='atwallet',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='authereum',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='bitkeep',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='bridgewallet',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='coin98',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='coinomi',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='coolwallets',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='dokwallet',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='easypocket',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='eidoo',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='equal',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='gridplus',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='huobiwallet',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='infinito',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='infinitywallet',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='mathwallet',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='meetone',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='metamask',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='midaswallet',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='morixwallet',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='mykey',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='nash',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='onto',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='others',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='ownbit',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='peakdefi',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='phantom',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='pillar',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='safepal',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='sfwtwallet',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='solana',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='sparkpoint',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='spatium',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='tokenary',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='tokenpocket',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='trust',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='unstoppablewallet',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='viawallet',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='vision',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='walleth',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='walletio',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='wazirx',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='xdcwallet',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='zelcore',
            name='passphrase',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
    ]
